{% set name = "pyfloc" %}
{% set version = "0.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58fc06ff91c1485e0f39c511c87b218fdc5c039edfd610769dc25764f4491b9f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - scikit-learn

test:
  imports:
    - pyfloc


about:
  home: https://github.com/pypa/sampleproject
  license: MIT
  license_family: MIT
  license_file: 
  summary: Data Mining analyses of flowcytometry data
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
